# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    redis_url: '%env(string:REDIS_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DTO/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\AppBundle\Doctrine\Migrations\IgnoreFksListener:
        tags:
            - {name: doctrine.event_listener, event: postGenerateSchema }

    GuzzleHttp\ClientInterface:
        factory: ['App\AppBundle\Factory\HttpClientFactory', 'createGuzzleClient']

    App\UseCase\Spotify\SpotifyHandler:
        arguments:
            $client: '@GuzzleHttp\ClientInterface'

    App\Command\TestCommand:
        arguments:
            $handler: '@App\UseCase\Spotify\SpotifyHandler'

    app.factory.redis:
        class: Predis\Client
        factory:
            - App\AppBundle\Factory\RedisConnectionFactory
            - createRedisClient
        arguments:
            - '%redis_url%'

    App\AppBundle\Manager\RedisManager:
        arguments:
            - '@app.factory.redis'

    App\Security\ApiKeyAuthenticator: